"""Typed exception hierarchy."""


class MusicDecoderError(Exception):
    """Base class for all music-decoder errors."""


class IngestError(MusicDecoderError): ...
class YouTubeError(IngestError): ...
class CorruptAudioError(IngestError): ...
class SilentAudioError(IngestError): ...
class ClipTooShortError(IngestError): ...

class SeparationError(MusicDecoderError): ...
class TranscriptionError(MusicDecoderError): ...
class ChordRecognitionError(MusicDecoderError): ...
class TabAssignmentError(MusicDecoderError): ...
class KeyDetectionError(MusicDecoderError): ...
class BeatTrackingError(MusicDecoderError): ...

class CompositionError(MusicDecoderError): ...
class InvalidScaleError(CompositionError): ...
class InvalidProgressionError(CompositionError): ...
class SynthesisError(MusicDecoderError): ...
